apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpass-secret"}},"mappingMethod":"claim","name":"developer","type":"HTPasswd"}],"templates":{"login":{"name":"login-template"}},"tokenConfig":{"accessTokenMaxAgeSeconds":31536000}}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-03-16T14:45:16Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 50a694ba-7ba7-4fc7-acce-c5eeb027aec4
  resourceVersion: "17793"
  uid: 40be093a-d69a-4b14-919c-28f4a2b83b3c
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: localusers
      mappingMethod: claim
      name: myusers
      type: HTPasswd
  templates:
    login:
      name: login-template
  tokenConfig:
    accessTokenMaxAgeSeconds: 31536000
